name: Publish Chrome

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Build v3
        run: npm run build-v3

      - name: Publish to Chrome Web Store
        run: npx chrome-webstore-upload-cli@3 --source web-ext-artifacts/progressiveimmersion_v3.zip
        env:
          EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CHROME_CLIENT }}
          CLIENT_SECRET: ${{ secrets.CHROME_SECRET }}
          REFRESH_TOKEN: ${{ secrets.CHROME_TOKEN }}
